### ISSUE TITLE
updated deps verison is ignored

### ISSUE THREAD

**Issue by stagfoo** [dsebastien/modernWebDevBuild#53]
Hi, so i updated the pacakge json and the jspm configs to use rjx alpha 14 instead of 7 because 7 has trouble with my machine, but even after changing the version it still requests 7. Is there another place I need to change it?

**Comment by dsebastien** [comment]
The problem is probably within JSPM's configuration because of Angular 2's transitive dependencies. You might be able to change all references to rxjs in jspm.conf.js but it might not work if APIs that Angular depends on have changed..

To be more precise, you'll find the RX version in the map, but also in `"npm:@reactivex/rxjs@5.0.0-alpha.7"` and also under `"npm:angular2@2.0.0-alpha.46": {`

I'm going to update this build and my project generator to the last alpha release of Angular 2 soon but first  I'd like to improve the testing story here :)
