### ISSUE TITLE
Sample for HTML5LocationStrategy

### ISSUE THREAD

**Issue by JanOschii** [dsebastien/modernWebDevBuild#84]
You have commented out the part with the html5LocationStrategy, but the code didnt work if you activate him. I can not find any HTML5LocationStrategy in the Angular 2 libraries.

BTW: Nice project!

**Comment by dsebastien** [comment]
Hey @JanOschii 

Actually that issue is in the project generator over at: https://github.com/dsebastien/modernWebDevGenerator

But you're right, HTML5LocationStrategy doesn't exist. The Angular team mentionned at some point that it should/would be renamed, but I guess it didn't after all. I'll remove that comment

**Comment by dsebastien** [comment]
I'll fix this in the generator through there: https://github.com/dsebastien/modernWebDevGenerator/issues/62
